version: "3"
services:
  lab:
    #image: jupyter_projname:v01 
    container_name: polio_ES_new
    build:
        context: .
        dockerfile: ./Dockerfile

    ports:
      - "8887:8888" 

    volumes:
      - .:/workdir
    command: start.sh jupyter lab